name: NgayXinh
options:
  bundleIdPrefix: vn.hiep4294
  deploymentTarget:
    iOS: "16.0"
settings:
  base:
    SWIFT_VERSION: "5.0"
targets:
  NgayXinh:
    type: application
    platform: iOS
    sources:
      - path: NgayXinh
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: vn.hiep4294.ngayxinh
        PRODUCT_NAME: NgayXinh
        INFOPLIST_FILE: NgayXinh/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        TARGETED_DEVICE_FAMILY: "1"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
    scheme:
      testTargets: []
